// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv92K77fyar9ofKhmYrHwpPqIt7YB4Auk',
    appId: '1:1024560540378:web:b645387badec0251bf13e3',
    messagingSenderId: '1024560540378',
    projectId: 'engess-chat-app',
    authDomain: 'engess-chat-app.firebaseapp.com',
    storageBucket: 'engess-chat-app.appspot.com',
    measurementId: 'G-H7VLMSL1WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3oV_7VeT0R_PVYRZhxZ4R4L34KxkjqI',
    appId: '1:1024560540378:android:208d0c858108f7d4bf13e3',
    messagingSenderId: '1024560540378',
    projectId: 'engess-chat-app',
    storageBucket: 'engess-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoSMQbEF6CgtUAWHlpPu6T1141uN2VmA4',
    appId: '1:1024560540378:ios:261d7172bea3e218bf13e3',
    messagingSenderId: '1024560540378',
    projectId: 'engess-chat-app',
    storageBucket: 'engess-chat-app.appspot.com',
    iosBundleId: 'com.example.engessChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoSMQbEF6CgtUAWHlpPu6T1141uN2VmA4',
    appId: '1:1024560540378:ios:261d7172bea3e218bf13e3',
    messagingSenderId: '1024560540378',
    projectId: 'engess-chat-app',
    storageBucket: 'engess-chat-app.appspot.com',
    iosBundleId: 'com.example.engessChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv92K77fyar9ofKhmYrHwpPqIt7YB4Auk',
    appId: '1:1024560540378:web:62786daf5527607ebf13e3',
    messagingSenderId: '1024560540378',
    projectId: 'engess-chat-app',
    authDomain: 'engess-chat-app.firebaseapp.com',
    storageBucket: 'engess-chat-app.appspot.com',
    measurementId: 'G-1X8X6Z3N45',
  );
}
